//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaProgrami
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pizza
    {
        public int id { get; set; }
        public string adı { get; set; }
        public string hamurTipi { get; set; }
        public Nullable<bool> domatesSosluMu { get; set; }
        public string Malzemeler { get; set; }
        public decimal fiyati { get; set; }
        public string boyutu { get; set; }
    }
}
